pre-commit hook that checks for encoding string (doesn't work in OSX right now unless you change xargs to gxargs)

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -3,74 +3,98 @@ failures=0
 
 ignorepep8=$(git config hooks.ignorepep8)
 if [ "$ignorepep8" != "true" ]; then
-	echo "Checking pep8..."
-	# Run pep8 on all touched .py files
-	pep8issues=0
-	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
-		# If this repo has a pep8-blacklist.txt, obey it
-		if [ -e "pep8-blacklist.txt" ]; then
-			if echo "$file" | grep -Ff pep8-blacklist.txt -q; then
-				continue
-			fi
-		fi
+    echo "Checking pep8..."
+    # Run pep8 on all touched .py files
+    pep8issues=0
+    for file in $(exec git diff --staged --name-only | grep '\.py$'); do
+        # If this repo has a pep8-blacklist.txt, obey it
+        if [ -e "pep8-blacklist.txt" ]; then
+            if echo "$file" | grep -Ff pep8-blacklist.txt -q; then
+                continue
+            fi
+        fi
 
-		if [[ -e "$file" && ! -h "$file" ]] && ! pep8 --ignore=E501,E126,E123 "$file"; then
-			pep8issues=1
-		fi
-	done
-	if [ $pep8issues == 1 ]; then
-		echo "pep8 reported issues."
-		failures=1
-	fi
+        if [[ -e "$file" && ! -h "$file" ]] && ! pep8 --ignore=E501,E126,E123 "$file"; then
+            pep8issues=1
+        fi
+    done
+    if [ $pep8issues == 1 ]; then
+        echo "pep8 reported issues."
+        failures=1
+    fi
 fi
 
 ignorepep257=$(git config hooks.ignorepep257)
 if [ "$ignorepep257" != "true" ]; then
-	echo "Checking pep257..."
-	# Run pep257 on all touched .py files
-	pep257issues=0
-	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
-		# If this repo has a pep257-blacklist.txt, obey it
-		if [ -e "pep257-blacklist.txt" ]; then
-			if echo "$file" | grep -Ff pep257-blacklist.txt -q; then
-				continue
-			fi
-		fi
+    echo "Checking pep257..."
+    # Run pep257 on all touched .py files
+    pep257issues=0
+    for file in $(exec git diff --staged --name-only | grep '\.py$'); do
+        # If this repo has a pep257-blacklist.txt, obey it
+        if [ -e "pep257-blacklist.txt" ]; then
+            if echo "$file" | grep -Ff pep257-blacklist.txt -q; then
+                continue
+            fi
+        fi
 
-		if [[ -e "$file" && ! -h "$file" ]] && ! pep257 "$file"; then
-			pep257issues=1
-		fi
-	done
-	if [ $pep257issues == 1 ]; then
-		echo "pep257 reported issues."
-		failures=1
-	fi
+        if [[ -e "$file" && ! -h "$file" ]] && ! pep257 "$file"; then
+            pep257issues=1
+        fi
+    done
+    if [ $pep257issues == 1 ]; then
+        echo "pep257 reported issues."
+        failures=1
+    fi
 fi
 
 ignorepyflakes=$(git config hooks.ignorepyflakes)
 if [ "$ignorepyflakes" != "true" ]; then
-	echo "Checking pyflakes..."
-	# Run pyflakes on all touched .py files
-	pyflakesissues=0
-	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
-		# If this repo has a pyflakes-blacklist.txt, obey it
-		if [ -e "pyflakes-blacklist.txt" ]; then
-			if echo "$file" | grep -Ff pyflakes-blacklist.txt -q; then
-				continue
-			fi
-		fi
+    echo "Checking pyflakes..."
+    # Run pyflakes on all touched .py files
+    pyflakesissues=0
+    for file in $(exec git diff --staged --name-only | grep '\.py$'); do
+        # If this repo has a pyflakes-blacklist.txt, obey it
+        if [ -e "pyflakes-blacklist.txt" ]; then
+            if echo "$file" | grep -Ff pyflakes-blacklist.txt -q; then
+                continue
+            fi
+        fi
 
-		if [[ -e "$file" && ! -h "$file" ]] && ! pyflakes "$file"; then
-			pyflakesissues=1
-		fi
-	done
-	if [ $pyflakesissues == 1 ]; then
-		echo "Pyflakes reported issues."
-		failures=1
-	fi
+        if [[ -e "$file" && ! -h "$file" ]] && ! pyflakes "$file"; then
+            pyflakesissues=1
+        fi
+    done
+    if [ $pyflakesissues == 1 ]; then
+        echo "Pyflakes reported issues."
+        failures=1
+    fi
+fi
+
+ignorepythonencoding=$(git config hooks.ignorepythonencoding)
+if [ "$ignorepythonencoding" != "true" ]; then
+    echo "Checking python script encodings..."
+    unencoded_python_files="$(
+        exec git diff --staged --name-only |
+        grep '.*\.py$' |
+        grep -v '/vendor/' |
+        xargs -P10 -I{} sh -c '
+                if [ -s {} ] && grep -q -m1 "[^[:space:]]" {} && ! head -2 {} | grep -q "^# -\*- coding: utf-8 -\*-$"; then
+                echo {}
+                fi
+        ' 2>&1 |
+        sort
+        )"
+
+    if [ "$unencoded_python_files" ]; then
+	echo "Expected the following encoding string in all python files:"
+        echo "# -*- coding: utf-8 -*-"
+	echo "Files missing pragma:"
+	printf -- '%s\n' "${unencoded_python_files[@]}"
+        failures=1
+    fi
 fi
 
 if [ $failures -ne 0 ]; then
-	echo "(Use 'git commit --no-verify' to bypass.)"
-	exit 1
+    echo "(Use 'git commit --no-verify' to bypass.)"
+    exit 1
 fi
